"""add patient_intake table

Revision ID: 651388c221da
Revises: 59d6b954bbb1
Create Date: 2026-07-14 17:23:01.437644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651388c221da'
down_revision: Union[str, None] = '59d6b954bbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_intakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('has_visited_before', sa.Boolean(), nullable=True),
    sa.Column('previous_doctor', sa.String(length=255), nullable=True),
    sa.Column('has_reports', sa.Boolean(), nullable=True),
    sa.Column('report_details', sa.Text(), nullable=True),
    sa.Column('current_medicines', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_intakes')
    # ### end Alembic commands ###
